services:
  - type: web
    name: n8n
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 3000
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
      - key: N8N_BASIC_AUTH_ACTIVE
        generateValue: true
      - key: N8N_BASIC_AUTH_USER
        generateValue: true
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: NODE_OPTIONS
        value: --max-old-space-size=256
    healthCheckPath: /health
