services:
  - type: web
    name: n8n
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      # --- Configuración básica del servidor ---
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https

      # --- URL pública (IMPORTANTE) ---
      - key: WEBHOOK_URL
        value: https://n8n-render-dev-21s5.onrender.com/

      # --- CORS para evitar bloqueos en Chrome ---
      - key: N8N_CORS_ALLOW_ORIGIN
        value: '*'

      # --- Optimización de memoria ---
      - key: NODE_OPTIONS
        value: --max-old-space-size=256

      # --- Configuración de base de datos PostgreSQL ---
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nSafeguard
          property: internalConnectionString
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nSafeguard
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nSafeguard
          property: password
      - key: DB_POSTGRESDB_DATABASE
        value: n8n

      # --- Autenticación básica (opcional, generada automáticamente) ---
      - key: N8N_BASIC_AUTH_ACTIVE
        generateValue: true
      - key: N8N_BASIC_AUTH_USER
        generateValue: true
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true

    # --- Ruta para verificar que el servicio está vivo ---
    healthCheckPath: /health

# --- Definición de la base de datos ---
databases:
  - name: n8nSafeguard
    plan: free
    region: oregon
    databaseName: n8n
